#
# Get configuration from managed hosts using "show running" command
#
---
- name:  Get device configuration
  hosts: all
  connection: local
  gather_facts: False
 
  tasks:
  # - name: Make sure we're in the right branch
  #   shell: git checkout {{branch|default('master')}}
  #   args:
  #     chdir: "{{repository}}"
  #   delegate_to: localhost
  #   run_once: true
  #   changed_when: no

  - name: Grab configuration
    ios_command:
      commands: show running
    register: cfg
  - set_fact: config={{ cfg.stdout[0]|regex_replace("\A[^!]*","") }}

  - name: Save configuration to local file
    copy:
      content: "{{config}}"
      dest: "{{repository}}/{{inventory_hostname}}.cfg"
    delegate_to: localhost
